#! /bin/sh

# use reconfigure -r to run autoreconf (passing any remaining
# arguments to it -- e.g., run "reconfigure -r -fvi") before
# reconfiguring

if [ "$1" = "-r" ] ; then
	shift
	autoreconf "$@"|| exit $?
fi

# this is the equivalent of invoking configure with all of its
# original arguments, useful after running autoreconf in an
# already-configured tree

./config.status --recheck && ./config.status
