version: '3'
services:
  devcontainer:
    build:
      dockerfile: ../Dockerfile
      target: devcontainer
    volumes:
      - ..:/workspace:cached
      - home:/me
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  home:
