import "Executive/IObject.idl";

[
        object,
        uuid(00000001-0000-0000-c000-000000000046),
        cheader("Executive/MFactory.h")
]
interface MFactory: IObject
{
    STATUS createInstance([in] IObject *outer, [in] REFUUID iid, [out,iid_is(iid)] void **object);
    STATUS lock([in] bool lock);
}
